# Generated by Django 5.2.1 on 2025-06-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_customermodel_customer_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loanmodel",
            name="loan_id",
            field=models.IntegerField(auto_created=True),
        ),
    ]
