# Generated by Django 5.2.1 on 2025-06-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_customermodel_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='customer_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
